### ISSUE TITLE
Potential scikit-learn version issue

### ISSUE THREAD

**Issue by jbae11** [mradaideh/neorl#15]
Hello, I followed the instructions in the readthedocs,
```
> conda create --name neorl python=3.7
> conda activate neorl
> pip install neorl
```

 and got the following error during `neorl --test`:

```
Traceback (most recent call last):
  File "/Users/4ib/anaconda3/envs/neorl/bin/neorl", line 5, in <module>
    from neorl.scripts import main
  File "/Users/4ib/anaconda3/envs/neorl/lib/python3.7/site-packages/neorl/scripts.py", line 42, in <module>
    from neorl.tune.runners.gridtune import GRIDTUNE
  File "/Users/4ib/anaconda3/envs/neorl/lib/python3.7/site-packages/neorl/tune/__init__.py", line 2, in <module>
    from neorl.tune.bayestune import BAYESTUNE
  File "/Users/4ib/anaconda3/envs/neorl/lib/python3.7/site-packages/neorl/tune/bayestune.py", line 30, in <module>
    from skopt import gp_minimize
  File "/Users/4ib/anaconda3/envs/neorl/lib/python3.7/site-packages/skopt/__init__.py", line 55, in <module>
    from .searchcv import BayesSearchCV
  File "/Users/4ib/anaconda3/envs/neorl/lib/python3.7/site-packages/skopt/searchcv.py", line 16, in <module>
    from sklearn.utils.fixes import MaskedArray
ImportError: cannot import name 'MaskedArray' from 'sklearn.utils.fixes' (/Users/4ib/anaconda3/envs/neorl/lib/python3.7/site-packages/sklearn/utils/fixes.py)
```

Seemed like it was a scikit-learn version problem:

Output of `conda list`:
```

scikit-learn              1.0.1                    pypi_0    pypi
scikit-optimize           0.8.1                    pypi_0    pypi

```

so I downgraded scikit-learn:
```
conda install scikit-learn=0.24.2
```

and now all the tests pass.

 I'm not sure if this is an issue so feel free to close it, but I thought this might help someone :)

**Comment by mradaideh** [comment]
Thank you @jbae11 yes it is definitely an issue that is arising after Scikit-learn update > 1.0.0,  I did not push the changes yet to restrict sklearn to <0.**, and I am expecting to do that in few days. Please, keep pointing out to any issues you find, this will be really helpful to others. Thank you for using NEORL!
